name: md_editor
description: >
  md_editor is a Flutter widget that provides an integrated Markdown editing experience. 
  It features a built-in toolbar for formatting and a live Markdown viewer, allowing users 
  to write, preview, and format Markdown content seamlessly within their Flutter applications. 
  Ideal for note-taking, documentation, or any app requiring Markdown support.
version: 0.0.1
homepage: https://labs.oresoftware.net/
repository: https://github.com/Ore-Software-Hub/flutter_md_editor.git

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
